version: '3'

services:
  nats:
    image: 'nats-streaming:0.20'
    entrypoint: '/gnatsd -DV'
    expose:
      - '4222'
    ports:
      - '8222:8222'
    networks:
      - neverfood-net
    hostname: nats-server

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - neverfood-net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - neverfood-net

  db:
    image: postgres:11.7-alpine
    expose:
      - '5432'
    restart: always
    environment:
      NODE_ENV: development
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
    networks:
      - neverfood-net

  restaurants:
    build:
      context: ./restaurants
      dockerfile: Dockerfile
    image: restaurants-srv:1.0.0
    restart: always
    ports:
      - '3004:3004'
    networks:
      - neverfood-net
    external_links:
      - db:db
    environment:
      POSTGRES_DB: neverfood_restaurantsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: db
    depends_on:
      - redis
      - mailhog
      - db
      - nats

volumes:
  database_data:
    driver: local

networks:
  neverfood-net:
    driver: bridge
